### ISSUE TITLE
Can't specify token's max age

### ISSUE THREAD

**Issue by Lauriero** [wgumenyuk/jwt-promisify#11]
Updated to a new version of the package and there's no longer maxAge option in jwt.verify VerifyOptions that allowed to specify expiration time

**Comment by wgumenyuk** [comment]
Great catch! A mistake on my end, I fixed it in commit [`5a43b7`](https://github.com/wgumenyuk/jwt-promisify/commit/5a43b7fec9a511de13c41a113cc0e86bc901389b). Thanks for your patience!
